import sys
sys.path.append('../')
from pycore.tikzeng import *
from pycore.blocks import *

arch = [
    # 开头
    to_head('..'),
    to_cor(),
    to_begin(),

    #　添加输入层
    to_input('./road.jpeg', width=9, height=9),
    # ---downsample----------------------------------------------------
    to_Conv(
        'downsample',
        s_filer=3,
        n_filer=3,
        offset="(0,0,0)",
        to="(0,0,0)",
        width=1,
        height=45,
        depth=45,
        # caption="PreConv",
    ),
    # ---CBM 1 ----------------------------------------------------
    to_yourConv(
        "CBM1_1",
        s_filer=3,
        n_filer=64,
        offset="(1,0,0)",
        to="(downsample-east)",
        width=3,
        height=40,
        depth=40,
        ConvColor=(5,10,5),
    ),
    to_yourConv(
        "CBM1_2",
        s_filer=32,
        n_filer=64,
        offset="(0,0,0)",
        to="(CBM1_1-east)",
        width=3,
        height=40,
        depth=40,
        ConvColor=(5,10,5),
    ),
    to_Pool("p1",
            offset="(1,0,0)",
            to="(CBM1_2-east)",
            width=1,
            height=32,
            depth=32,
            opacity=0.5),
    # ---CBM 2 ----------------------------------------------------
    to_yourConv(
        "CBM2_1",
        s_filer=32,
        n_filer=64,
        offset="(1,0,0)",
        to="(p1-east)",
        width=3,
        height=32,
        depth=32,
        ConvColor=(5,10,5),
    ),
    to_yourConv(
        "CBM2_2",
        s_filer=32,
        n_filer=64,
        offset="(0,0,0)",
        to="(CBM2_1-east)",
        width=3,
        height=32,
        depth=32,
        ConvColor=(5,10,5),
    ),
    to_Pool("p2",
            offset="(1,0,0)",
            to="(CBM2_2-east)",
            width=1,
            height=25,
            depth=25,
            opacity=0.5),
    # ---CBM 3 ----------------------------------------------------
    to_yourConv(
        "CBM3_1",
        s_filer=32,
        n_filer=64,
        offset="(1,0,0)",
        to="(p2-east)",
        width=3,
        height=25,
        depth=25,
        ConvColor=(5,10,5),
    ),
    to_yourConv(
        "CBM3_2",
        s_filer=32,
        n_filer=64,
        offset="(0,0,0)",
        to="(CBM3_1-east)",
        width=3,
        height=25,
        depth=25,
        ConvColor=(5,10,5),
    ),
    to_Pool("p3",
            offset="(1,0,0)",
            to="(CBM3_2-east)",
            width=1,
            height=16,
            depth=16,
            opacity=0.5),
    # ---CBM 4 ----------------------------------------------------
    to_yourConv(
        "CBM4_1",
        s_filer=32,
        n_filer=64,
        offset="(1,0,0)",
        to="(p3-east)",
        width=3,
        height=16,
        depth=16,
        ConvColor=(5,10,5),
    ),
    to_yourConv(
        "CBM4_2",
        s_filer=32,
        n_filer=64,
        offset="(0,0,0)",
        to="(CBM4_1-east)",
        width=3,
        height=16,
        depth=16,
        ConvColor=(5,10,5),
    ),

    # ---编码链接----------------------------------------------------
    to_connection('downsample', "CBM1_1"),
    to_connection("CBM1_2", "p1"),
    to_connection('p1', "CBM2_1"),
    to_connection("CBM2_2", "p2"),
    to_connection('p2', "CBM3_1"),
    to_connection("CBM3_2", "p3"),
    to_connection('p3', "CBM4_1"),

    # ---Concat ----------------------------------------------------
    to_yourConv("concat_all",
              s_filer="",
              n_filer="",
              offset="(5,0,0)",
              to="(CBM4_2-east)",
              width=12,
              height=42,
              depth=42,
              caption="Concat",
              ConvColor=(5,3,10),
              ),
    to_DeConv("concat4",
            s_filer="",
            n_filer="",
            offset="(0.3,0,0)",
            to="(concat_all-west)",
            width=1,
            height=40,
            depth=40),
    to_DeConv("concat3",
            s_filer="",
            n_filer="",
            offset="(0.3,0,0)",
            to="(concat4-east)",
            width=1,
            height=40,
            depth=40),
    to_DeConv("concat2",
            s_filer="",
            n_filer="",
            offset="(0.3,0,0)",
            to="(concat3-east)",
            width=1,
            height=40,
            depth=40),
    to_Conv("concat1",
            s_filer="",
            n_filer="",
            offset="(0.3,0,0)",
            to="(concat2-east)",
            width=1,
            height=40,
            depth=40),

    # ---upsample pool ----------------------------------------------------
    to_Conv("upsample_pool1",
            s_filer=32,
            n_filer=64,
            offset="(2,0,25)",
            to="(p1-east)",
            width=1,
            height=40,
            depth=40,
            caption="Conv",
            ),
    *to_sideskip("CBM1_2", "p1", "upsample_pool1", "concat1", 25),
    to_DeConv(
        "upsample_pool2",
        s_filer=32,
        n_filer=64,
        offset="(2,0,20)",
        to="(p2-east)",
        width=1,
        height=40,
        depth=40,
        caption="DeConv",
    ),
    *to_sideskip("CBM2_2", "p2", "upsample_pool2", "concat2", 20),
    to_DeConv(
        "upsample_pool3",
        s_filer=32,
        n_filer=64,
        offset="(2,0,15)",
        to="(p3-east)",
        width=1,
        height=40,
        depth=40,
        caption="DeConv",
    ),
    *to_sideskip("CBM3_2", "p3", "upsample_pool3", "concat3", 15),
    to_DeConv(
        "upsample_pool4",
        s_filer=32,
        n_filer=64,
        offset="(2,0,10)",
        to="(CBM4_2-east)",
        width=1,
        height=40,
        depth=40,
        caption="DeConv",
    ),
    *to_sideskip("CBM4_2", "CBM4_2", "upsample_pool4", "concat4", 10),

    # ---fcn ----------------------------------------------------
    to_Conv("fcn1",
            s_filer=256,
            n_filer=1024,
            offset="(2,0,0)",
            to="(concat_all-east)",
            width=5,
            height=40,
            depth=40),
    to_Conv("fcn2",
            s_filer=1024,
            n_filer=2,
            offset="(2,0,0)",
            to="(fcn1-east)",
            width=1,
            height=40,
            depth=40),
    to_DeConv("upsample_out",
            s_filer=2,
            n_filer=2,
            offset="(2,0,0)",
            to="(fcn2-east)",
            width=1,
            height=45,
            depth=45),
    to_connection("concat_all","fcn1"),
    to_connection("fcn1","fcn2"),
    to_connection("fcn2","upsample_out"),
    
    to_input('./lab.jpeg',offset=2,
            to="(upsample_out-east)", width=9, height=9),

    #  结束
    to_end(),
]


def main():
    namefile = str(sys.argv[0]).split('.')[0]
    to_generate(arch, namefile + '.tex')


if __name__ == '__main__':
    main()
